# Generated by Django 4.1.3 on 2022-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0002_alter_enfermedad_descripcion_alter_enfermedad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
